import type {
  RecoveryCause,
  SessionEndState,
  SignalKind,
} from '@/entities/nodeDetail';
import type { NodeState } from '@/entities/nodeState';
import { DagState } from '@/utils/dagState';

export const NODE_STATE_LABELS: Record<NodeState, string> = {
  pending: 'Pending',
  in_progress: 'In progress',
  resting: 'Resting',
  merged: 'Merged',
  needs_human: 'Needs human',
  errored: 'Errored',
  skipped: 'Skipped',
};

export const DAG_STATE_LABELS: Record<DagState, string> = {
  [DagState.ANY]: 'All',
  [DagState.ACTIVE]: 'Active',
  [DagState.COMPLETE]: 'Complete',
  [DagState.ERRORED]: 'Errored',
};

export const SESSION_END_STATE_LABELS: Record<SessionEndState, string> = {
  alive: 'Running',
  finished: 'Finished',
  overdue: 'Overdue',
  aborted: 'Aborted',
};

export const RECOVERY_CAUSE_LABELS: Record<RecoveryCause, string> = {
  turn_cap_reached: 'Turn cap reached',
  background_wait_terminated: 'Background wait terminated',
  usage_limit: 'Usage limit',
  provider_failure: 'Provider failure',
  process_killed: 'Process killed',
  no_pull_request: 'No pull request',
  overdue: 'Overdue',
  workspace_inconsistent: 'Workspace inconsistent',
};

export const SIGNAL_LABELS: Record<SignalKind, string> = {
  pr: 'Pull request',
  comments: 'Comments',
  checks: 'Checks',
  approval: 'Approval',
  conflict: 'Conflict',
};

export const NODE_STATE_LABELS_LOWERCASE: Record<NodeState, string> = {
  pending: 'pending',
  in_progress: 'in progress',
  resting: 'resting',
  merged: 'merged',
  needs_human: 'needs human',
  errored: 'errored',
  skipped: 'skipped',
};

export const LABELS = {
  appTitle: 'virgo-dag',
  appDescription: 'The dags this host records.',
  apiRequestFailed:
    'The api request failed. This screen shows the last data that arrived.',
  apiRequestFailedTitle: 'The api does not respond',
  apiRequestFailedHint:
    'Start it with dagctl serve. This screen loads as soon as it responds.',
  dagsLoading: 'Loading the dags',
  dagLoading: 'Loading the dag',
  nodeLoading: 'Loading the node',
  dagsHeading: 'DAGS',
  dagsEmpty:
    'No dags on this host. Start one with dagctl start --dag <path to dag.toml>.',
  dagsEmptyHint: 'Dags are read from ~/.virgo-dag.',
  dagStateFilter: 'Filter the dags by state',
  dagsFilteredEmpty: 'No dags in this state.',
  dagsFilteredEmptyHint: 'Choose All to see every dag on this host.',
  dagNodeCount: '{count} nodes',
  dagBaseBranch: 'Base branch',
  dagUnreadable: 'database unreadable',
  dagScheduledOn: 'Host job registered',
  dagScheduledOff: 'No host job registered',
  dagWatchingOn: 'Watcher running',
  dagWatchingOff: 'Watcher stopped',
  dagNeverActive: 'No activity recorded',
  nodeStateCount: '{state} {count}',
  nodeStateCountLowercase: '{count} {state}',
  dagListCollapse: 'Collapse the dag list',
  dagListExpand: 'Expand the dag list',
  dagListOpen: 'Show the dag list',
  dagListBack: 'Back to the dag list',
  notFoundTitle: 'Page not found',
  notFoundEmpty: 'This url matches no screen.',
  notFoundEmptyHint: 'Every dag on this host is in the dag list.',
  splitResize: 'Resize the panels',
  dagUnreadableTitle: 'This dag cannot be read',
  dagUnreadableHint:
    'Its database would not open. Every other dag on this host still loads.',
  dagAudit: 'Activity',
  dagNodes: 'Nodes',
  dagMemory: 'Memory',
  dagSettings: 'Settings',
  dagAuditEmpty: 'No audit entries yet',
  dagAuditEmptyHint:
    'An entry is written every time the controller moves a node to a new state.',
  dagNodesEmpty: 'No nodes in this dag',
  dagNodesEmptyHint: 'Nodes come from the dag.toml this dag was started with.',
  dagMemoryLoading: 'Loading the memory file',
  dagMemoryEmpty: 'No memory yet',
  dagMemoryEmptyHint:
    "A learning session writes the memory file after a node's pull request is merged or closed.",
  dagMemoryUpdatedAt: 'updated {time}',
  dagTickInterval: 'Tick interval',
  nodeState: 'State',
  nodeId: 'Node',
  nodeTitle: 'Title',
  nodeAgent: 'Agent',
  nodeLastActivity: 'Last activity',
  nodePullRequest: 'Has a pull request',
  nodeOpen: 'Open the node',
  durationSeconds: '{count} seconds',
  durationMinutes: '{count} minutes',
  themeToggle: 'Switch between light and dark',
  notBuiltTitle: 'Not built yet',
  notBuiltBody: 'This page arrives with the next node.',
  nodeBack: 'Back to the dag',
  nodeUnknown: 'This dag records no node with that id.',
  nodeWakes: 'wake {wakes}',
  nodeUpdatedAt: 'updated {time}',
  nodePullRequestLink: 'Pull request',
  nodeNoPullRequest: 'No pull request opened yet',
  sessionFailureHeading: 'Session failure',
  sessionExitCode: 'exit {code}',
  recoveryRetryAt: 'retry {time}',
  recoveryUnrecoverable: 'Not recoverable',
  nodesLabel: 'Nodes',
  nodesEmpty: 'This dag records no nodes.',
  conversationHeading: 'Conversation',
  conversationEmpty: 'No conversation to show',
  conversationEmptyHint: 'The transcript of this node has no message to show.',
  conversationWiden: 'Widen the conversation',
  conversationNarrow: 'Narrow the conversation',
  subagentThreads: 'Subagent threads',
  subagentThread: 'Subagent',
  userMessageTitle: 'Prompt',
  agentMessageTitle: 'Agent',
  sessionWake: 'Wake {wake}',
  sessionStartedAt: 'started {time}',
  toolUnnamed: 'Tool',
  toolResultHeading: 'Result',
  toolNoInput: 'This call was made without arguments.',
  toolCommandLabel: 'Command',
  toolFileLabel: 'File',
  toolContentLabel: 'Content',
  toolBeforeLabel: 'Before',
  toolAfterLabel: 'After',
  dependsOnHeading: 'Depends on',
  blocksHeading: 'Blocks',
  dependenciesEmpty: 'None',
  worktreeHeading: 'Worktree',
  worktreeNone: 'No worktree was cut for this node.',
  worktreePath: 'Path',
  worktreeBranch: 'Branch',
  worktreePullRequest: 'Pull request',
  worktreePullRequestNumber: '#{number}',
  worktreeNoPullRequest: 'None',
  worktreeCut: 'Cut',
  worktreeDisk: 'Disk',
  worktreeReclaimedAt: 'reclaimed {time}',
  worktreeOnDisk: 'Still on disk',
  signalMarksHeading: 'Delivery marks',
  signalMarksEmpty: 'No signal has been acted on yet.',
  slackNotificationsHeading: 'Slack notifications',
  slackNotificationsEmpty: 'Nothing has been sent about this node.',
  slackNotificationThread: 'thread {threadId}',
  sessionsHeading: 'Sessions',
  sessionsEmpty: 'This node has not woken yet.',
  sessionRunning: 'Running',
  sessionsWakeColumn: 'Wake',
  sessionsStartedColumn: 'Started',
  sessionsEndColumn: 'End state',
  sessionsJump: 'Show wake {wake} in the conversation',
  instructionsHeading: 'Instructions',
  instructionsEmpty: 'This node was launched without instructions.',
  instructionsViewMore: 'View more',
  instructionsViewLess: 'View less',
} as const;
