"""The package-wide named constants of virgo-agentic-dag."""

from __future__ import annotations

DAGCTL_ENVIRONMENT_VARIABLE_NAMES = (
    "PATH",
    "HOME",
    "USER",
    "LOGNAME",
    "SHELL",
    "TMPDIR",
    "LANG",
)
DEFAULT_CONVERSATION_PAGE_LIMIT = 50
MAX_CONVERSATION_PAGE_LIMIT = 200
NODE_ACTION_TIMEOUT_SECONDS = 30
RUN_LOCK_RETRY_INTERVAL_SECONDS = 0.1
STOPPED_SESSION_END_STATE = "stopped"
TRANSCRIPT_BLOCK_SIZE_BYTES = 65_536
